<?xml version='1.0' encoding='UTF-8'?><wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://service.webserviceclientandservice.frankxu.demo.com" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns2="http://schemas.xmlsoap.org/soap/http" xmlns:ns1="http://service.webserviceclientandservice.frankxu.demo.com/" name="UserService" targetNamespace="http://service.webserviceclientandservice.frankxu.demo.com">
  <wsdl:import location="http://127.0.0.1:8086/soap/user?wsdl=UserService.wsdl" namespace="http://service.webserviceclientandservice.frankxu.demo.com/">
    </wsdl:import>
  <wsdl:binding name="UserServiceSoapBinding" type="ns1:UserService">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="getUserName">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="getUserName">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="getUserNameResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="getUser">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="getUser">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="getUserResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="UserService">
    <wsdl:port binding="tns:UserServiceSoapBinding" name="UserServiceImplPort">
      <soap:address location="http://127.0.0.1:8086/soap/user"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>