
package cn.chinaunicom.ws.baiduintelligenceser;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import cn.chinaunicom.ws.baiduintelligenceser.unibssbody.BAIDUORDERRELATIONNOTIFYINPUT;
import cn.chinaunicom.ws.baiduintelligenceser.unibssbody.BAIDUORDERRELATIONNOTIFYOUTPUT;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BaiduIntelligenceSer", targetNamespace = "http://ws.chinaunicom.cn/BaiduIntelligenceSer/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    cn.chinaunicom.ws.unibsshead.ObjectFactory.class,
    cn.chinaunicom.ws.baiduintelligenceser.unibssbody.ObjectFactory.class,
    cn.chinaunicom.ws.baiduintelligenceser.unibssbody.baiduorderrelationnotifyreq.ObjectFactory.class,
    cn.chinaunicom.ws.baiduintelligenceser.unibssbody.baiduorderrelationnotifyrsp.ObjectFactory.class,
    cn.chinaunicom.ws.unibssattached.ObjectFactory.class
})
public interface BaiduIntelligenceSer {


    /**
     * 
     * @param parameters
     * @return
     *     returns cn.chinaunicom.ws.baiduintelligenceser.unibssbody.BAIDUORDERRELATIONNOTIFYOUTPUT
     */
    @WebMethod(action = "http://ws.chinaunicom.cn/BaiduIntelligenceSer/baiduOrderRelationNotify/")
    @WebResult(name = "BAIDU_ORDER_RELATION_NOTIFY_OUTPUT", targetNamespace = "http://ws.chinaunicom.cn/BaiduIntelligenceSer/unibssBody", partName = "parameters")
    public BAIDUORDERRELATIONNOTIFYOUTPUT baiduOrderRelationNotify(
        @WebParam(name = "BAIDU_ORDER_RELATION_NOTIFY_INPUT", targetNamespace = "http://ws.chinaunicom.cn/BaiduIntelligenceSer/unibssBody", partName = "parameters")
        BAIDUORDERRELATIONNOTIFYINPUT parameters);

}
